MVC.Web/Controllers/FormsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Primitives;
using MVC.Web.Models.Products;
using MVC.Web.Models.Products.ViewModels;
using MVC.Web.Models.Services;

namespace MVC.Web.Controllers
{
    public class FormsController : Controller
    {
        [HttpGet]
        public IActionResult FormExample1()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FormExample1Post()
        {
            #region 1.way

            string firstName = Request.Form["firstName"]!;
            string lastName = Request.Form["lastName"]!;
            string age = Request.Form["age"]!;

            #endregion

            #region 2. way

            if (Request.Form.TryGetValue("firstName", out StringValues firstNameValue))
            {
            }

            #endregion

            #region 3. way

            if (Request.Form.ContainsKey("firstName"))
            {
                string firstName2 = Request.Form["firstName"]!;
            }

            #endregion


            return RedirectToAction("FormExample1");
        }
    }
}

MVC.Web/Views/Forms/CreateProduct.cshtml
@{
    ViewData["Title"] = "CreateProduct";
}
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model MVC.Web.Models.Products.ViewModels.ProductCreateWrapperModel
<h1>CreateProduct</h1>

<form asp-controller="Forms" asp-action="CreateProduct" method="post">
    
    <div class="mb-3">
        <label asp-for="CategoryViewModel.CategorySelectList"  class="form-label"></label>
        @*   <input class="form-control" asp-for="CategoryViewModel.Name" placeholder="kategori ismi"> *@
        
        <select class="form-control"  asp-for="CategoryViewModel.CategoryId" asp-items="Model.CategoryViewModel.CategorySelectList"></select>
    </div>
    

    <div class="mb-3">
        <label asp-for="ProductViewModel.Name"  class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.Name" placeholder="ürün ismi">
    </div>
    
    <div class="mb-3">
        <label asp-for="ProductViewModel.Price" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.Price" placeholder="ürün fiyat">
    </div>
    
    <div class="mb-3">
        <label asp-for="ProductViewModel.Description" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.Description" placeholder="ürün açıklama">
    </div>
    
    <div class="mb-3">
        <label asp-for="ProductViewModel.StockCount" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.StockCount" placeholder="ürün stok adet">
    </div>
    
    <div class="mb-3">
        <label asp-for="ProductViewModel.PictureUrl" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.PictureUrl" placeholder="ürün resim url">
    </div>
    <div>
       <button class="btn btn-primary" type="submit">Kaydet</button>
    </div>
</form>

MVC.Web/Views/Forms/FormExample1.cshtml
@{
    ViewData["Title"] = "FormExample1";
}
@*  Server Side App *@
<h1>FormExample1</h1>


<form asp-controller="Forms" asp-action="FormExample1Post" method="post">
    
    <input  name="firstName"/>
    <hr/>
    <input name="lastName"/>
    
    <hr/>
    <input name="age"/> 
    
    
    
    <button type="submit">Kaydet</button>

</form>

MVC.Web/Views/Forms/ProductList.cshtml
@{
    ViewData["Title"] = "ProductList";
}
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model List<MVC.Web.Models.Products.ViewModels.ProductViewModel>
<h1>ProductList</h1>
<a class="btn btn-primary" asp-controller="Forms" asp-action="CreateProduct">Create Product</a>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Description
            </th>
            <th>
                StockCount
            </th>
            <th>
                PictureUrl
            </th>
            
            <th>
                IsPublisher
            </th>
            <th>Publish Duration</th>
            <th>Category Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img style="width: 100px; height: 100px;"  src="/pictures/@item.PictureUrl"/>
                 
                </td>
                

                <td>
                    @item.Name
                </td>
                <td>
                    @item.Price
                </td>
                <td>
                    @item.Description
                </td>
                <td>
                    @item.StockCount
                </td>

                <td>
                    @item.IsPublisher
                </td>
                <td>
                    @item.PublishDuration
                </td>
                <td>
                    @item.CategoryName
                </td>
                <td>
                    
                    <a asp-controller="Forms" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    
                    
                    <a asp-controller="Forms" asp-action="UpdateProduct" asp-route-id="@item.Id">Update</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MVC.Web/Views/Forms/UpdateProduct.cshtml
@{
    ViewData["Title"] = "UpdateProduct";
}
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model MVC.Web.Models.Products.ViewModels.ProductUpdateWrapperModel
<h1>CreateProduct</h1>

<form asp-controller="Forms" asp-action="UpdateProduct" method="post" enctype="multipart/form-data">


    <div class="mb-3">
        <label asp-for="ProductViewModel.ImageFile" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.ImageFile">
    </div>


    <div class="mb-3">
        <label asp-for="CategoryViewModel.CategorySelectList" class="form-label"></label>
        @*   <input class="form-control" asp-for="CategoryViewModel.Name" placeholder="kategori ismi"> *@

        <select class="form-control" asp-for="CategoryViewModel.CategoryId" asp-items="Model.CategoryViewModel.CategorySelectList"></select>
    </div>


    <div class="mb-3">
        <label asp-for="ProductViewModel.Name" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.Name" placeholder="ürün ismi">
    </div>

    <div class="mb-3">
        <label asp-for="ProductViewModel.Price" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.Price" placeholder="ürün fiyat">
    </div>

    <div class="mb-3">
        <label asp-for="ProductViewModel.Description" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.Description" placeholder="ürün açıklama">
    </div>

    <div class="mb-3">
        <label asp-for="ProductViewModel.StockCount" class="form-label"></label>
        <input class="form-control" asp-for="ProductViewModel.StockCount" placeholder="ürün stok adet">
    </div>

    @*  <div class="mb-3">
    <label asp-for="ProductViewModel.PictureUrl" class="form-label"></label>
    <input class="form-control" asp-for="ProductViewModel.PictureUrl" placeholder="ürün resim url">
    </div> *@


    <div class="form-check">
        <input class="form-check-input" asp-for="ProductViewModel.IsPublish">
        <label class="form-check-label" asp-for="ProductViewModel.IsPublish">

        </label>
    </div>

    <div>

        @foreach (var isPublisherDuration in Model.ProductViewModel.IsPublisherDurationList)
        {


            <div class="form-check">
                <input   asp-for="ProductViewModel.IsPublisherDurationId" class="form-check-input" type="radio" value="@isPublisherDuration.Value" checked=@(Model.ProductViewModel.IsPublisherChecked(isPublisherDuration.Value))>
               
                
                <label class="form-check-label" for="flexRadioDefault2">
                    @isPublisherDuration.Text
                </label>
            </div>
        }


    </div>














    <div>
        <button class="btn btn-primary" type="submit">Güncelle</button>
    </div>
</form>